### PR TITLE
Bug fix on PHP 7.2 later

### PR DESCRIPTION
**Pull request by tarikhagustia**
i have issue while using this package on PHP 7.2 later, please review this PL

### CODE REVIEW

**Comment by jamesdordoy** [comment]
Thank you for correcting this.

**Comment by tarikhagustia** [comment]
np, please create new tags @jamesdordoy

**Comment by jamesdordoy** [comment]
Released under 1.3.4 @tarikhagustia

**Comment by jamesdordoy** [comment]
@tarikhagustia Please use 1.3.5 as it includes additional bugfixes and thrown exceptions.

**Pull request merged**
